ktor:
    application:
        modules:
            - app.netlify.cazterk.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    issuer: "http://localhost:8080"
    domain: "http://localhost:8080"
    audience: "users"
    realm: "ktor sample app"
